/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package moe.umlgui.ui.object;

import java.util.HashMap;
import java.util.Iterator;
import javax.swing.DefaultComboBoxModel;
import moe.umlgui.model.CoreObject;
import moe.umlgui.model.CoreObjectMethod;
import moe.umlgui.model.Project;

/**
 *
 * @author Moe
 */
public class CoreObjectMethodSelector extends javax.swing.JPanel {

    Project project;
    CoreObjectMethod selectedMethod;
    
    
    
    /**
     * Creates new form BusinessObjectPropertySelector
     */
    public CoreObjectMethodSelector(Project project) {
        this.project = project;
        initComponents();
        loadSelector();
    }
    
    
    /**
     * Creates new form BusinessObjectPropertySelector
     */
    public CoreObjectMethodSelector(Project project , CoreObjectMethod method) {
        this.project = project;
        this.selectedMethod = method;
        initComponents();
        loadSelector();
    }
    
    HashMap<String,CoreObjectMethod> propMap = new HashMap();
    
    private void loadSelector(){
        for(Iterator<CoreObject> i = project.getCoreObjects().iterator() ; i.hasNext();){
            CoreObject bo = i.next();
            for(Iterator<CoreObjectMethod> j = bo.getMethods().iterator() ; j.hasNext() ; ){
                CoreObjectMethod m = j.next();
                propMap.put(m.toFullString(), m);
                ((DefaultComboBoxModel)jComboBox1.getModel()).addElement(m.toFullString());
                jComboBox1.setSelectedItem(m.toFullString());
            }
        }
    }

    public CoreObjectMethod getSelectedMethod() {
        return selectedMethod;
    }

    public int getSelectedIndex(){
        return jComboBox1.getSelectedIndex();
    }
    
    public void setSelectedMethod(CoreObjectMethod selectedMethod) {
        this.selectedMethod = selectedMethod;
        if(selectedMethod!=null){
            jComboBox1.setSelectedItem(selectedMethod.toFullString());
        }
        else{
            jComboBox1.setSelectedItem(null);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        newButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jComboBox1.setModel(new DefaultComboBoxModel());
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, java.awt.BorderLayout.CENTER);

        newButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moe/umlgui/img/16x16/Add.png"))); // NOI18N
        add(newButton, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if(jComboBox1.getSelectedItem()!=null){
            selectedMethod = propMap.get(jComboBox1.getSelectedItem());
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JButton newButton;
    // End of variables declaration//GEN-END:variables
}
