/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package moe.umlgui.ui;

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import javax.swing.border.TitledBorder;
import javax.swing.event.ListDataListener;
import moe.umlgui.model.*;

/**
 *
 * @author Moe
 */
public class DiagramExplorer extends javax.swing.JPanel {

    UmlDiagram umlDiagram;
    
    /**
     * Creates new form DiagramExplorer
     */
    public DiagramExplorer() {
        initComponents();
    }

    Project project;
    
    public void setProject(Project project){
        this.project = project;
    }
    
    
    public void exploreDiagram(UmlDiagram umlDiagram){
        this.umlDiagram = umlDiagram;
        loadDiagram();
    }
    
    private ListModel elementListModel = new ListModel(){
        @Override
        public int getSize() {
            if(umlDiagram != null)  return umlDiagram.getElementList().size();
            return 0;
        }

        @Override
        public Object getElementAt(int index) {
            return umlDiagram.getElementList().get(index);
        }

        ArrayList<ListDataListener> listDataListeners = new ArrayList();
        @Override
        public void addListDataListener(ListDataListener l) {
            listDataListeners.add(l);
        }

        @Override
        public void removeListDataListener(ListDataListener l) {
            listDataListeners.remove(l);
        }
        
    };
    
    private void loadDiagram(){    
        setBorder(new TitledBorder(umlDiagram.getName()));
        revalidate();        
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        elementJList = new javax.swing.JList<>();
        jToolBar1 = new javax.swing.JToolBar();
        moveUpButton = new javax.swing.JButton();
        moveDownButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        elementJList.setModel(elementListModel);
        jScrollPane1.setViewportView(elementJList);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);

        moveUpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moe/umlgui/img/go-up.png"))); // NOI18N
        moveUpButton.setText("Move Up");
        moveUpButton.setToolTipText("Move Up");
        moveUpButton.setFocusable(false);
        moveUpButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        moveUpButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(moveUpButton);

        moveDownButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moe/umlgui/img/go-down.png"))); // NOI18N
        moveDownButton.setText("Move Down");
        moveDownButton.setToolTipText("Move Down");
        moveDownButton.setFocusable(false);
        moveDownButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        moveDownButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(moveDownButton);

        add(jToolBar1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> elementJList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton moveDownButton;
    private javax.swing.JButton moveUpButton;
    // End of variables declaration//GEN-END:variables
}
