/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package moe.umlgui.ui;

import java.awt.BorderLayout;
import javax.swing.DefaultComboBoxModel;
import moe.umlgui.model.*;

/**
 *
 * @author Moe
 */
public class LogicalTestComponent extends javax.swing.JPanel {

    LogicalTest test;
    Project context;
    
    /**
     * Creates new form LogicalTestComponent
     */
    public LogicalTestComponent(LogicalTest test , Project context) {
        this.test = test;
        this.context = context;
        initComponents();
        load();
    }
    
    BusinessObjectPropertySelector propSelector;

    private void load(){
        propSelector = new BusinessObjectPropertySelector(context);
        jPanel1.add(propSelector , BorderLayout.CENTER);
        
        if(test.getCondition()!=null) conditionComboBox.setSelectedItem(test.getCondition());
        if(test.getOperandA()!=null)    propSelector.setSelectedProperty(test.getOperandA());
        if(test.getOperator()!=null) jComboBox1.setSelectedItem(test.getOperator());
        if(test.getOperandB()!=null)    jTextField2.setText(test.getOperandB());
        if(test.getLabel() != null) labelTextField.setText(test.getLabel());
    }
    
    //TODO VALIDATE
    public void save(){
        test.setCondition((String)conditionComboBox.getSelectedItem());
        test.setOperandA(propSelector.getSelectedProperty());
        test.setOperator((String)jComboBox1.getSelectedItem());
        test.setOperandB(jTextField2.getText());
        test.setLabel(labelTextField.getText());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        conditionComboBox = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        labelTextField = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        conditionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IF", "ELSE IF", "ELSE" }));
        conditionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conditionComboBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(conditionComboBox, gridBagConstraints);

        jPanel1.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(jPanel1, gridBagConstraints);

        jComboBox1.setModel(new DefaultComboBoxModel(LogicalTest.OPERATORS));
        jComboBox1.setSelectedItem(test.getOperator());
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new java.awt.GridBagConstraints());

        jTextField2.setText(test.getOperandB());
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(jTextField2, gridBagConstraints);

        jLabel1.setText("Connector Label: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(labelTextField, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        /*if(jComboBox1.getSelectedItem().equals("IS") ||
            jComboBox1.getSelectedItem().equals("=")
        ){
            labelTextField.setEnabled(false);
            labelTextField.setText(null);
        }
        else{
            labelTextField.setEnabled(true);
            if(test.getLabel() != null) labelTextField.setText(test.getLabel());
        }*/
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void conditionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conditionComboBoxActionPerformed
        if(conditionComboBox.getSelectedItem().equals("ELSE")){
            propSelector.setEnabled(false);
            propSelector.setSelectedProperty(null);
            jComboBox1.setEnabled(false);
            jComboBox1.setSelectedItem(null);
            jTextField2.setEnabled(false);
            jTextField2.setText(null);
        }
        else{
            propSelector.setEnabled(true);
            jComboBox1.setEnabled(true);
            jTextField2.setEnabled(true);
            if(test.getOperandA()!=null)    propSelector.setSelectedProperty(test.getOperandA());
            if(test.getOperator()!=null) jComboBox1.setSelectedItem(test.getOperator());
            if(test.getOperandB()!=null)    jTextField2.setText(test.getOperandB());
        }
    }//GEN-LAST:event_conditionComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> conditionComboBox;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField labelTextField;
    // End of variables declaration//GEN-END:variables
}
