/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package moe.umlgui.ui;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.border.TitledBorder;
import moe.umlgui.model.*;
import moe.umlgui.ui.tree.Explorer;
import moe.umlgui.ui.tree.ExplorerTreeCellRenderer;
import moe.umlgui.ui.tree.ExplorerTreeModel;

/**
 *
 * @author Moe
 */
public class ProjectExplorer extends javax.swing.JPanel implements PropertyChangeListener{

    
    /**
     * Creates new form ProjectExplorer
     */
    public ProjectExplorer() {
        initComponents();
    }
    
    Project project;
    Explorer explorer;
    HashMap<UmlDiagram, DiagramExplorer> openDiagramExplorers = new HashMap();
    HashMap<UmlDiagram, UmlDiagramPanel> openDiagramPanels = new HashMap();
    
    public void explore(Project project){
        this.project = project;
        loadProject();
    }

    private void loadProject(){        
        //setBorder(new TitledBorder(project.getName()));
        
        propertyEditor.setContext(project);
        //palette.setProject(project);
        
        explorer = new Explorer(project);      
        explorer.addPropertyChangeListener(this);
        jSplitPane2.setTopComponent(explorer);
        propertyEditor.addPropertyChangeListener(this);
        
        revalidate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        propertyEditorScrollPane = new javax.swing.JScrollPane();
        propertyEditor = new moe.umlgui.ui.PropertyEditor();

        setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moe/umlgui/img/24x24/DiagramNew.PNG"))); // NOI18N
        jLabel1.setText("New Diagram: ");
        jToolBar1.add(jLabel1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Use Case Diagram", "Activity Diagram", "Sequence Diagram", "Package Diagram" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jComboBox1);

        add(jToolBar1, java.awt.BorderLayout.NORTH);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jSplitPane2.setDividerLocation(100);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane2.setBottomComponent(jTabbedPane1);

        jSplitPane1.setLeftComponent(jSplitPane2);

        propertyEditorScrollPane.setViewportView(propertyEditor);

        jSplitPane1.setRightComponent(propertyEditorScrollPane);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        UmlDiagram ud = null;
        
        if(jComboBox1.getSelectedItem().equals("Use Case Diagram")){
            ud = new UseCaseDiagram(project.getModels().get(0));            
        }
        else if(jComboBox1.getSelectedItem().equals("Activity Diagram")){
            ud = new ActivityDiagram(project.getModels().get(0));
        }
        else if(jComboBox1.getSelectedItem().equals("Sequence Diagram")){
            ud = new SequenceDiagram(project.getModels().get(0));
        }
        else if(jComboBox1.getSelectedItem().equals("Package Diagram")){
            ud = new PackageDiagram(project.getModels().get(0));
        }
        
        if(ud !=  null){
            project.getDiagrams().add(ud);
            project.getModels().get(0).getDiagrams().add(ud);
            
            propertyEditor.edit(ud);
            
            DiagramExplorer diagramExplorer = new DiagramExplorer();
            diagramExplorer.setProject(project);
            diagramExplorer.exploreDiagram(ud);
            diagramExplorer.addPropertyChangeListener(this);
            addPropertyChangeListener(diagramExplorer);
            openDiagramExplorers.put(ud, diagramExplorer);
            
            jTabbedPane1.addTab(ud.getName(), diagramExplorer);
            
            UmlDiagramPanel dp = new UmlDiagramPanel(ud);
            dp.addPropertyChangeListener(this);
            dp.addPropertyChangeListener(diagramExplorer);
            addPropertyChangeListener(dp);
            diagramExplorer.addPropertyChangeListener(dp);
            openDiagramPanels.put(ud, dp);
            
            ArrayList q =new ArrayList();
            q.add(this);
            this.firePropertyChange("Display", q, dp);
            
            revalidate();
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private moe.umlgui.ui.PropertyEditor propertyEditor;
    private javax.swing.JScrollPane propertyEditorScrollPane;
    // End of variables declaration//GEN-END:variables

    
    
    public boolean equals(Object o){
        return (hashCode()==o.hashCode());
    }
    
    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        if(!evt.getPropertyName().equals("Element updated") &&
            !evt.getPropertyName().equals("Diagram updated")  &&
            !evt.getPropertyName().equals("Project updated") &&
            !evt.getPropertyName().equals("Element inserted")  &&
            !evt.getPropertyName().equals("Explorer selection") 
        ){
            return;
        }
        
        //PropertyEditor events
        if(evt.getPropertyName().equals("Element updated") && !((ArrayList)evt.getOldValue()).contains(this)){
            ((ArrayList)evt.getOldValue()).add(this);
            this.firePropertyChange("Element updated", evt.getOldValue(), evt.getNewValue());
            explorer.reload();
        }
        else if(evt.getPropertyName().equals("Diagram updated") && !((ArrayList)evt.getOldValue()).contains(this)){
            ((ArrayList)evt.getOldValue()).add(this);
            explorer.reload();
        }
        else if(evt.getPropertyName().equals("Project updated") &&!((ArrayList)evt.getOldValue()).contains(this)){
            
        }
        
        //DiagramPanel / diagramExplorer events
        else if(evt.getPropertyName().equals("Element inserted") && !((ArrayList)evt.getOldValue()).contains(this)){
            ((ArrayList)evt.getOldValue()).add(this);
            UmlCoreElement el = (UmlCoreElement)evt.getNewValue();
            project.addCoreElement(el);
            propertyEditor.edit(el);            
            explorer.reload();
        }
        
        else if(evt.getPropertyName().equals("Explorer selection") && !((ArrayList)evt.getOldValue()).contains(this)){
            ((ArrayList)evt.getOldValue()).add(this);
            
            if(Project.class.isInstance(evt.getNewValue())){
                propertyEditor.edit((Project)evt.getNewValue());
            }
            else if(UmlModel.class.isInstance(evt.getNewValue())){
                propertyEditor.edit((UmlModel)evt.getNewValue());
            }
            else if(UmlDiagram.class.isInstance(evt.getNewValue())){
                UmlDiagram ud = (UmlDiagram)evt.getNewValue();
                propertyEditor.edit(ud);
                
                DiagramExplorer diagramExplorer = openDiagramExplorers.get(ud);
                if(diagramExplorer==null){
                    diagramExplorer = new DiagramExplorer();                
                    diagramExplorer.setProject(project);
                    diagramExplorer.exploreDiagram(ud);
                    diagramExplorer.addPropertyChangeListener(this);
                    addPropertyChangeListener(diagramExplorer);
                    openDiagramExplorers.put(ud, diagramExplorer);
                    jTabbedPane1.addTab(ud.getName(), diagramExplorer);
                }
                jTabbedPane1.setSelectedComponent(diagramExplorer);
                
                UmlDiagramPanel dp = openDiagramPanels.get(ud);
                if(dp==null){
                    dp = new UmlDiagramPanel(ud);
                    dp.addPropertyChangeListener(this);
                    dp.addPropertyChangeListener(diagramExplorer);
                    addPropertyChangeListener(dp);
                    diagramExplorer.addPropertyChangeListener(dp);
                    openDiagramPanels.put(ud, dp);
                }
                
                ArrayList q =new ArrayList();
                q.add(this);
                this.firePropertyChange("Display", q, dp);

                explorer.reload();
                revalidate();
            }
            else if(UmlCoreElement.class.isInstance(evt.getNewValue())){
                propertyEditor.edit((UmlCoreElement)evt.getNewValue());
            }
        }
    }
}
