/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package moe.umlgui.ui;

import moe.umlgui.model.*;
import java.awt.BorderLayout;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.TitledBorder;
import moe.umlgui.controller.PUMLDriver;

/**
 *
 * @author Moe
 */
public class UmlDiagramPanel extends javax.swing.JPanel  implements PropertyChangeListener{

    UmlDiagram umlDiagram;
    
    /**
     * Creates new form UmlDiagramPanel
     */
    public UmlDiagramPanel(UmlDiagram umlDiagram){
        super();
        this.umlDiagram = umlDiagram;
        
        initComponents();
        loadDiagramPanel();
        this.setTransferHandler(new UmlElementImportTransferHandler(umlDiagram));
    }
    
    private void loadDiagramPanel(){
        setName(umlDiagram.getName());        
        this.setBorder(new TitledBorder(umlDiagram.getName()));
        this.revalidate();
    }
    
    
    public void updateImage(){
        removeAll();
        JLabel l = new JLabel();
        l.setIcon(new ImageIcon(umlDiagram.getImage()));
        add(l, BorderLayout.CENTER);
        revalidate();
       
    }
    
    public void insertElement(UmlCoreElement el) throws IOException{
        umlDiagram.addCoreElement(el);
        updateImage();
        this.firePropertyChange("Element inserted", null, el);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        if(evt.getPropertyName().equals("Element updated") &&
                umlDiagram.getCoreElementMap().containsKey(((UmlCoreElement)evt.getNewValue()).getId())
        ){
            try {
                PUMLDriver.update(umlDiagram);
                updateImage();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, ".");
            }
        }
        
        else if(evt.getPropertyName().equals("Diagram updated")){
            loadDiagramPanel();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
